version: '3'

services:
  web:
    image: 'kafunelu-dungeon'
    build:
      context: .
    container_name: kafunelu-dungeon
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/kafunelu
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '8080:8080'
  db:
    image: 'postgres'
    container_name: 'kafunelu-dungeon-postgres'
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=kafunelu
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'